services:
  ollama:
    image: ollama/ollama:0.5.7
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
      - ./ollama_entrypoint.sh:/ollama_entrypoint.sh
    ports:
      - "11434:11434"
    environment:
      - LLM_MODEL_VERSION=${LLM_MODEL_VERSION}
    entrypoint: ["/bin/bash", "/ollama_entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  server:
    build:
      context: ./Server
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - ./.env
    networks:
      - default



volumes:
  ollama:
  
